services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-db-password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-db-password
    depends_on:
      - mongo

volumes:
  mongodb_data: 