services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app